<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class PromotionSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $promotions = [
            // Buy One Get One Free = 8
            // Large -> 3, 6, 9, 12,
            // Medium -> 2, 5, 8, 11,
            [
                'size_id' => 3,
                'name' => 'Buy One Get One Free',
                'code' => 'BOGOF',
                'type' => 'number_of_items_validation',
                'value' => 2,
                'price_type' => 'percentage',
                'price_value' => '0',
                'description' => 'Buy One Get One Free when buying 2 Medium Named Pizza or 2 Large Named Pizza',
                'delivery_method' => 'collection or delivery',
                'is_active' => 1,
            ],
            [
                'size_id' => 6,
                'name' => 'Buy One Get One Free',
                'code' => 'BOGOF',
                'type' => 'number_of_items_validation',
                'value' => 2,
                'price_type' => 'percentage',
                'price_value' => '0',
                'description' => 'Buy One Get One Free when buying 2 Medium Named Pizza or 2 Large Named Pizza',
                'delivery_method' => 'collection or delivery',
                'is_active' => 1,
            ],
            [
                'size_id' => 9,
                'name' => 'Buy One Get One Free',
                'code' => 'BOGOF',
                'type' => 'number_of_items_validation',
                'value' => 2,
                'price_type' => 'percentage',
                'price_value' => '0',
                'description' => 'Buy One Get One Free when buying 2 Medium Named Pizza or 2 Large Named Pizza',
                'delivery_method' => 'collection or delivery',
                'is_active' => 1,
            ],
            [
                'size_id' => 12,
                'name' => 'Buy One Get One Free',
                'code' => 'BOGOF',
                'type' => 'number_of_items_validation',
                'value' => 2,
                'price_type' => 'percentage',
                'price_value' => '0',
                'description' => 'Buy One Get One Free when buying 2 Medium Named Pizza or 2 Large Named Pizza',
                'delivery_method' => 'collection or delivery',
                'is_active' => 1,
            ],
            [
                'size_id' => 2,
                'name' => 'Buy One Get One Free',
                'code' => 'BOGOF',
                'type' => 'number_of_items_validation',
                'value' => 2,
                'price_type' => 'percentage',
                'price_value' => '0',
                'description' => 'Buy One Get One Free when buying 2 Medium Named Pizza or 2 Large Named Pizza',
                'delivery_method' => 'collection or delivery',
                'is_active' => 1,
            ],
            [
                'size_id' => 5,
                'name' => 'Buy One Get One Free',
                'code' => 'BOGOF',
                'type' => 'number_of_items_validation',
                'value' => 2,
                'price_type' => 'percentage',
                'price_value' => '0',
                'description' => 'Buy One Get One Free when buying 2 Medium Named Pizza or 2 Large Named Pizza',
                'delivery_method' => 'collection or delivery',
                'is_active' => 1,
            ],
            [
                'size_id' => 8,
                'name' => 'Buy One Get One Free',
                'code' => 'BOGOF',
                'type' => 'number_of_items_validation',
                'value' => 2,
                'price_type' => 'percentage',
                'price_value' => '0',
                'description' => 'Buy One Get One Free when buying 2 Medium Named Pizza or 2 Large Named Pizza',
                'delivery_method' => 'collection or delivery',
                'is_active' => 1,
            ],
            [
                'size_id' => 11,
                'name' => 'Buy One Get One Free',
                'code' => 'BOGOF',
                'type' => 'number_of_items_validation',
                'value' => 2,
                'price_type' => 'percentage',
                'price_value' => '0',
                'description' => 'Buy One Get One Free when buying 2 Medium Named Pizza or 2 Large Named Pizza',
                'delivery_method' => 'collection or delivery',
                'is_active' => 1,
            ],

            // ***************************************************************
            // Three for Two = 4
            // Medium -> 2, 5, 8, 11,
            [
                'size_id' => 2,
                'name' => 'Three for Two',
                'code' => '3FOR2',
                'type' => 'number_of_items_validation',
                'value' => 3,
                'price_type' => 'percentage',
                'price_value' => '33',
                'description' => 'Buy 2 & Get 1 Free',
                'delivery_method' => 'collection or delivery',
                'is_active' => 1,
            ],
            [
                'size_id' => 5,
                'name' => 'Three for Two',
                'code' => '3FOR2',
                'type' => 'number_of_items_validation',
                'value' => 3,
                'price_type' => 'percentage',
                'price_value' => '33',
                'description' => 'Buy 2 & Get 1 Free',
                'delivery_method' => 'collection or delivery',
                'is_active' => 1,
            ],
            [
                'size_id' => 8,
                'name' => 'Three for Two',
                'code' => '3FOR2',
                'type' => 'number_of_items_validation',
                'value' => 3,
                'price_type' => 'percentage',
                'price_value' => '33',
                'description' => 'Buy 2 & Get 1 Free',
                'delivery_method' => 'collection or delivery',
                'is_active' => 1,
            ],
            [
                'size_id' => 11,
                'name' => 'Three for Two',
                'code' => '3FOR2',
                'type' => 'number_of_items_validation',
                'value' => 3,
                'price_type' => 'percentage',
                'price_value' => '33',
                'description' => 'Buy 2 & Get 1 Free',
                'delivery_method' => 'collection or delivery',
                'is_active' => 1,
            ],

            // ***************************************************************
            // Family Feast = 4
            // Medium -> 2, 5, 8, 11
            [
                'size_id' => 2,
                'name' => 'Family Feast',
                'code' => 'FAMILYFEAST',
                'type' => 'number_of_items_validation',
                'value' => 4,
                'price_type' => 'fixed',
                'price_value' => '30',
                'description' => 'Buy 4 Medium Set Menu Pizzas just for £30',
                'delivery_method' => 'collection',
                'is_active' => 1,
            ],
            [
                'size_id' => 5,
                'name' => 'Family Feast',
                'code' => 'FAMILYFEAST',
                'type' => 'number_of_items_validation',
                'value' => 4,
                'price_type' => 'fixed',
                'price_value' => '30',
                'description' => 'Buy 4 Medium Set Menu Pizzas just for £30',
                'delivery_method' => 'collection',
                'is_active' => 1,
            ],
            [
                'size_id' => 8,
                'name' => 'Family Feast',
                'code' => 'FAMILYFEAST',
                'type' => 'number_of_items_validation',
                'value' => 4,
                'price_type' => 'fixed',
                'price_value' => '30',
                'description' => 'Buy 4 Medium Set Menu Pizzas just for £30',
                'delivery_method' => 'collection',
                'is_active' => 1,
            ],
            [
                'size_id' => 11,
                'name' => 'Family Feast',
                'code' => 'FAMILYFEAST',
                'type' => 'number_of_items_validation',
                'value' => 4,
                'price_type' => 'fixed',
                'price_value' => '30',
                'description' => 'Buy 4 Medium Set Menu Pizzas just for £30',
                'delivery_method' => 'collection',
                'is_active' => 1,
            ],

            // ***************************************************************
            // Two Large = 4
            // Large -> 3, 6, 9, 12,
            [
                'size_id' => 3,
                'name' => 'Two Large',
                'code' => '2LARGE',
                'type' => 'number_of_items_validation',
                'value' => 2,
                'price_type' => 'fixed',
                'price_value' => '25',
                'description' => 'Buy 2 Large Set Menu Pizzas just for £25',
                'delivery_method' => 'collection',
                'is_active' => 1,
            ],
            [
                'size_id' => 6,
                'name' => 'Two Large',
                'code' => '2LARGE',
                'type' => 'number_of_items_validation',
                'value' => 2,
                'price_type' => 'fixed',
                'price_value' => '25',
                'description' => 'Buy 2 Large Set Menu Pizzas just for £25',
                'delivery_method' => 'collection',
                'is_active' => 1,
            ],
            [
                'size_id' => 9,
                'name' => 'Two Large',
                'code' => '2LARGE',
                'type' => 'number_of_items_validation',
                'value' => 2,
                'price_type' => 'fixed',
                'price_value' => '25',
                'description' => 'Buy 2 Large Set Menu Pizzas just for £25',
                'delivery_method' => 'collection',
                'is_active' => 1,
            ],
            [
                'size_id' => 12,
                'name' => 'Two Large',
                'code' => '2LARGE',
                'type' => 'number_of_items_validation',
                'value' => 2,
                'price_type' => 'fixed',
                'price_value' => '25',
                'description' => 'Buy 2 Large Set Menu Pizzas just for £25',
                'delivery_method' => 'collection',
                'is_active' => 1,
            ],

            // ***************************************************************
            // Two Medium = 4
            // Medium -> 2, 5, 8, 11,
            [
                'size_id' => 2,
                'name' => 'Two Medium',
                'code' => '2MEDIUM',
                'type' => 'number_of_items_validation',
                'value' => 2,
                'price_type' => 'fixed',
                'price_value' => '18',
                'description' => 'Buy 2 Medium Set Menu Pizzas just for £18',
                'delivery_method' => 'collection',
                'is_active' => 1,
            ],
            [
                'size_id' => 5,
                'name' => 'Two Medium',
                'code' => '2MEDIUM',
                'type' => 'number_of_items_validation',
                'value' => 2,
                'price_type' => 'fixed',
                'price_value' => '18',
                'description' => 'Buy 2 Medium Set Menu Pizzas just for £18',
                'delivery_method' => 'collection',
                'is_active' => 1,
            ],
            [
                'size_id' => 8,
                'name' => 'Two Medium',
                'code' => '2MEDIUM',
                'type' => 'number_of_items_validation',
                'value' => 2,
                'price_type' => 'fixed',
                'price_value' => '18',
                'description' => 'Buy 2 Medium Set Menu Pizzas just for £18',
                'delivery_method' => 'collection',
                'is_active' => 1,
            ],
            [
                'size_id' => 11,
                'name' => 'Two Medium',
                'code' => '2MEDIUM',
                'type' => 'number_of_items_validation',
                'value' => 2,
                'price_type' => 'fixed',
                'price_value' => '18',
                'description' => 'Buy 2 Medium Set Menu Pizzas just for £18',
                'delivery_method' => 'collection',
                'is_active' => 1,
            ],

            // ***************************************************************
            // Two Small = 4
            // Medium -> 1, 4, 7, 10,
            [
                'size_id' => 1,
                'name' => 'Two Small',
                'code' => '2SMALL',
                'type' => 'number_of_items_validation',
                'value' => 2,
                'price_type' => 'fixed',
                'price_value' => '12',
                'description' => 'Buy 2 Small Set Menu Pizzas just for £12',
                'delivery_method' => 'collection',
                'is_active' => 1,
            ],
            [
                'size_id' => 4,
                'name' => 'Two Small',
                'code' => '2SMALL',
                'type' => 'number_of_items_validation',
                'value' => 2,
                'price_type' => 'fixed',
                'price_value' => '12',
                'description' => 'Buy 2 Small Set Menu Pizzas just for £12',
                'delivery_method' => 'collection',
                'is_active' => 1,
            ],
            [
                'size_id' => 7,
                'name' => 'Two Small',
                'code' => '2SMALL',
                'type' => 'number_of_items_validation',
                'value' => 2,
                'price_type' => 'fixed',
                'price_value' => '12',
                'description' => 'Buy 2 Small Set Menu Pizzas just for £12',
                'delivery_method' => 'collection',
                'is_active' => 1,
            ],
            [
                'size_id' => 10,
                'name' => 'Two Small',
                'code' => '2SMALL',
                'type' => 'number_of_items_validation',
                'value' => 2,
                'price_type' => 'fixed',
                'price_value' => '12',
                'description' => 'Buy 2 Small Set Menu Pizzas just for £12',
                'delivery_method' => 'collection',
                'is_active' => 1,
            ],

        ];

        foreach ($promotions as $promotion) {
            \App\Models\Promotion::create($promotion);
        }
    }
}
